
// This file has been generated by the GUI designer. Do not modify.
namespace EntretienAuto
{
	public partial class FicheVehicule
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBoxEntry comboboxentryMarque;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ComboBoxEntry comboboxentryModele;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry entryImmatriculation;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry entryPMC;
		
		private global::Gtk.Entry entryAchat;
		
		private global::Gtk.Entry entryVente;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry entryMIN;
		
		private global::Gtk.ComboBoxEntry comboboxentryEnergie;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry entryChassis;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry entryTypeMoteur;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.ComboBoxEntry comboboxentryCouleur;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Entry entryPFiscale;
		
		private global::Gtk.Entry entryPCV;
		
		private global::Gtk.Entry entryPKw;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EntretienAuto.FicheVehicule
			this.Name = "EntretienAuto.FicheVehicule";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child EntretienAuto.FicheVehicule.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Marque: ");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w2.X = 23;
			w2.Y = 15;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentryMarque = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryMarque.Name = "comboboxentryMarque";
			this.fixed1.Add (this.comboboxentryMarque);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentryMarque]));
			w3.X = 89;
			w3.Y = 9;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Modele:");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 25;
			w4.Y = 52;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentryModele = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryModele.Name = "comboboxentryModele";
			this.fixed1.Add (this.comboboxentryModele);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentryModele]));
			w5.X = 89;
			w5.Y = 47;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Immatriculation:");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w6.X = 23;
			w6.Y = 95;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryImmatriculation = new global::Gtk.Entry ();
			this.entryImmatriculation.CanFocus = true;
			this.entryImmatriculation.Name = "entryImmatriculation";
			this.entryImmatriculation.IsEditable = true;
			this.entryImmatriculation.InvisibleChar = '•';
			this.fixed1.Add (this.entryImmatriculation);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryImmatriculation]));
			w7.X = 143;
			w7.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Date de premiere mise en circulation:");
			this.label5.Wrap = true;
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w8.X = 310;
			w8.Y = 14;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Date d'achat:");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w9.X = 469;
			w9.Y = 49;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Date de vente:");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w10.X = 463;
			w10.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryPMC = new global::Gtk.Entry ();
			this.entryPMC.CanFocus = true;
			this.entryPMC.Name = "entryPMC";
			this.entryPMC.IsEditable = true;
			this.entryPMC.InvisibleChar = '•';
			this.fixed1.Add (this.entryPMC);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryPMC]));
			w11.X = 569;
			w11.Y = 9;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryAchat = new global::Gtk.Entry ();
			this.entryAchat.CanFocus = true;
			this.entryAchat.Name = "entryAchat";
			this.entryAchat.IsEditable = true;
			this.entryAchat.InvisibleChar = '•';
			this.fixed1.Add (this.entryAchat);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryAchat]));
			w12.X = 569;
			w12.Y = 47;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryVente = new global::Gtk.Entry ();
			this.entryVente.CanFocus = true;
			this.entryVente.Name = "entryVente";
			this.entryVente.IsEditable = true;
			this.entryVente.InvisibleChar = '•';
			this.fixed1.Add (this.entryVente);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryVente]));
			w13.X = 569;
			w13.Y = 85;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero MIN:");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w14.X = 47;
			w14.Y = 137;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryMIN = new global::Gtk.Entry ();
			this.entryMIN.CanFocus = true;
			this.entryMIN.Name = "entryMIN";
			this.entryMIN.IsEditable = true;
			this.entryMIN.InvisibleChar = '•';
			this.fixed1.Add (this.entryMIN);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryMIN]));
			w15.X = 143;
			w15.Y = 133;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentryEnergie = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryEnergie.Name = "comboboxentryEnergie";
			this.fixed1.Add (this.comboboxentryEnergie);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentryEnergie]));
			w16.X = 116;
			w16.Y = 212;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Energie:");
			this.fixed1.Add (this.label9);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
			w17.X = 50;
			w17.Y = 216;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Couleur:");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w18.X = 50;
			w18.Y = 254;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryChassis = new global::Gtk.Entry ();
			this.entryChassis.CanFocus = true;
			this.entryChassis.Name = "entryChassis";
			this.entryChassis.IsEditable = true;
			this.entryChassis.InvisibleChar = '•';
			this.fixed1.Add (this.entryChassis);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryChassis]));
			w19.X = 143;
			w19.Y = 173;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero Chassis:");
			this.fixed1.Add (this.label10);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
			w20.X = 24;
			w20.Y = 177;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryTypeMoteur = new global::Gtk.Entry ();
			this.entryTypeMoteur.CanFocus = true;
			this.entryTypeMoteur.Name = "entryTypeMoteur";
			this.entryTypeMoteur.IsEditable = true;
			this.entryTypeMoteur.InvisibleChar = '•';
			this.fixed1.Add (this.entryTypeMoteur);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryTypeMoteur]));
			w21.X = 569;
			w21.Y = 125;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Type moteur:");
			this.fixed1.Add (this.label11);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
			w22.X = 471;
			w22.Y = 129;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentryCouleur = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryCouleur.Name = "comboboxentryCouleur";
			this.fixed1.Add (this.comboboxentryCouleur);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentryCouleur]));
			w23.X = 116;
			w23.Y = 250;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Puissance fiscale:");
			this.fixed1.Add (this.label13);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label13]));
			w24.X = 444;
			w24.Y = 166;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryPFiscale = new global::Gtk.Entry ();
			this.entryPFiscale.CanFocus = true;
			this.entryPFiscale.Name = "entryPFiscale";
			this.entryPFiscale.IsEditable = true;
			this.entryPFiscale.InvisibleChar = '•';
			this.fixed1.Add (this.entryPFiscale);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryPFiscale]));
			w25.X = 569;
			w25.Y = 163;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryPCV = new global::Gtk.Entry ();
			this.entryPCV.CanFocus = true;
			this.entryPCV.Name = "entryPCV";
			this.entryPCV.IsEditable = true;
			this.entryPCV.InvisibleChar = '•';
			this.fixed1.Add (this.entryPCV);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryPCV]));
			w26.X = 569;
			w26.Y = 246;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryPKw = new global::Gtk.Entry ();
			this.entryPKw.CanFocus = true;
			this.entryPKw.Name = "entryPKw";
			this.entryPKw.IsEditable = true;
			this.entryPKw.InvisibleChar = '•';
			this.fixed1.Add (this.entryPKw);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryPKw]));
			w27.X = 569;
			w27.Y = 205;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Puissance (CV):");
			this.fixed1.Add (this.label15);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label15]));
			w28.X = 458;
			w28.Y = 250;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Puissance (Kw):");
			this.fixed1.Add (this.label14);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label14]));
			w29.X = 459;
			w29.Y = 207;
			w1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
			w30.Position = 0;
			// Internal child EntretienAuto.FicheVehicule.ActionArea
			global::Gtk.HButtonBox w31 = this.ActionArea;
			w31.Name = "dialog1_ActionArea";
			w31.Spacing = 10;
			w31.BorderWidth = ((uint)(5));
			w31.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31 [this.buttonCancel]));
			w32.Expand = false;
			w32.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31 [this.buttonOk]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 746;
			this.DefaultHeight = 341;
			this.Show ();
		}
	}
}
