M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu23.04.1} date jeu. 23 mai 2024 10:10:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-23T10:10:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X71.5Y-72.75
X71.5Y-117.25
X225.0Y-72.75
X225.0Y-117.25
M30
